import java.util.HashMap;

public class wordbook {
    HashMap<String, String> eng = new HashMap<>();

    public wordbook () {
        this.eng = new HashMap<>();
        eng.put("abdicate","To abdicate is to renounce or relinquish a position of usually sovereign power. It can also mean “to cast off; discard.”");
        eng.put("augur","To augur is to show or suggest, especially from omens, that something might happen in the future. Used most often in formal speech or writing, augur is often followed by an adverb (such as well). ");
        eng.put("bravado","Bravado refers to confident or brave talk or behavior that is intended to impress other people.");
        eng.put("celerity","Celerity is a formal word that means “swiftness of motion or action.”");
        eng.put("compadre","A compadre is a person’s close friend or buddy.");
        eng.put("cornucopia","A cornucopia, also known as a horn of plenty, is a curved, hollow goat’s horn or similarly shaped receptacle (such as a horn-shaped basket) that is overflowing, especially with fruit and vegetables. The image of a cornucopia is commonly used as decoration and as a symbol of abundance, but the word cornucopia is today more often encountered in its metaphorical use referring to an overflowing abundance, or to a seemingly inexhaustible amount of something. ");
        eng.put("diminuitive", "small");
        eng.put("expeditius","Expeditious is a formal word that is used to describe someone acting in a quick and efficient way, or something done in such a manner");
        eng.put("extirpate","Extirpate means “to destroy completely,” and is often—though not exclusively—used in reference to plant and animal populations. It can also be used to mean “to pull up by the root” and “to cut out by surgery.");
        eng.put("farce","A farce is a ridiculous act, proceeding, or situation. Farce can also refer to a light dramatic work marked by satirical comedy and improbable plot, or the broad humor characteristic of such. The word can also refer to a savory stuffing.");
        eng.put("fidiciary","Fiduciary is a formal word meaning \"relating to or involving trust (such as the trust between a customer and a professional).\"");
        eng.put("gloaming","Gloaming is a literary term synonymous with twilight and dusk, the darker part of twilight. It's used most commonly in the noun phrase the gloaming.");
        eng.put("hummock", "A hummock is a small round hill or mound.");
        eng.put("imbue","imbue can be used as a synonym for endow (“to provide with something freely or naturally”) and can also mean “to permeate or influence” in a way that suggests colored dye permeating cloth fabric. ");
        eng.put("jejune","Jejune is a formal word often used as a synonym of juvenile to describe things (such as behaviors, attitudes, etc.) that are immature, childish, or simplistic. It can also mean \"uninteresting\" or \"boring.\"");
        eng.put("lachrymose","Lachrymose is used to describe someone who tends to cry often, or something that tends to cause people to cry.");
        eng.put("leonine","Leonine means “of, relating to, or resembling a lion.”");
        eng.put("motley","Motley usually means \"made up of many different people or things,\" and often appears in the phrase \"motley crew\" or \"motley mix.\" It can also mean \"variegated in color.\"");
        eng.put("morass", "Morass is used literally to refer to an area of soft, wet ground, especially a marsh or swamp. It is also often used figuratively to mean “a complicated or unpleasant situation that is difficult to get out of or to move through.” ");
        eng.put("nugatory","Something described as nugatory is of little or no consequence. Nugatory is also used especially in legal contexts to describe something without operative legal effect.");
        eng.put("onomatopeia","Onomatopoeia means “the creation or use of words that imitate sounds.” It can also refer to the words themselves.");
        eng.put("pell-mell","Pell-mell means “in a confused and hurried way” or “in mingled confusion or disorder.”");
        eng.put("perceptible","Perceptible means “able to be seen or noticed.”");
        eng.put("putative", "Putative is a formal word meaning \"generally believed, supposed, or assumed to be (something).\" It is always used before a noun. ");
        eng.put("quidity","Quiddity refers to the essence of a thing—that is, whatever makes something the type of thing that it is. Quiddity can also refer to a small and usually trivial complaint or criticism, or to a quirk or eccentricity in someone's behavior.");
        eng.put("sandbag","When used figuratively, sandbag usually means “to hit or stun as if with a sandbag,” “to criticize or treat unfairly” or “to hide one’s true abilities or purpose in order to deceive people, gain an advantage, etc.");
        eng.put("temerity","Temerity is a formal word that means \"unreasonable or foolhardy contempt of danger or opposition\"; it is a synonym of both rashness and recklessness. Temerity can also refer to a rash or reckless act.");
        eng.put("solace","Solace means “someone or something that gives a feeling of comfort to a person who is experiencing grief, sadness, or anxiety.” ");
        eng.put("sustain","Sustain means \"to provide what is needed for something or someone to exist or continue; to nourish.");
        eng.put("undulat","Undulate is a formal word that means “to move or be shaped like waves.”");
        eng.put("vandalize","Vandalize means “to deliberately damage or destroy public or private property.”");
        eng.put("wheedle","Wheedle means \"to use soft words or flattery,\" usually for the purpose of persuading someone to do something or to give you something. It is often used disapprovingly, and is frequently followed by the word into, as in \"wheedle one's way into favor.\"");
        eng.put("magnanimous","Magnanimous is a formal word that means “having or showing a generous and kind nature.”");
        eng.put("crucible","Crucible refers to a place or situation that forces someone or something to change. ");
        eng.put("intoxicate","Intoxicate means \"to excite or stupefy by or as if by alcohol or drugs.\" It can also mean \"to poison.\"");
        eng.put("doughty","Doughty means “brave, strong, and determined.”");
        eng.put("lapidary","Lapidary is used to describe something that is elegant and precise");
        eng.put("bilious","Bilious has several meanings, including \"angry or bad-tempered\" and \"sickeningly unpleasant to look at.\"");
        eng.put("encapsulate","Encapsulate means “to show or express the main idea or quality of (something) in a brief way.” ");
        eng.put("serendipity","Serendipity is luck that takes the form of finding valuable or pleasant things that are not looked for.");
        eng.put("gauche","When describing a person or a behavior, gauche can mean “socially awkward” or “tactless”; when describing an object it can mean “crudely made or done.”");
        eng.put("abandon","Abandon means “a feeling or attitude of wild or complete freedom,” and is often used synonymously with enthusiasm and exuberance. ");
        eng.put("catcorner","Catercorner is used as both an adverb and adjective to describe things that are situated in a diagonal or oblique position.");
        eng.put("rapscallion","The word rapscallion refers to someone who causes trouble, often in a mischievous way");
        eng.put("fustigate","Fustigate means “to criticize severely.”");
        eng.put("sallow","Sallow means \"of a grayish greenish yellow color,\" and often suggests sickliness.");
        eng.put("lyncantrophy","Lycanthropy refers to the power or ability to take the shape and characteristics of a wolf through witchcraft or magic.");
        eng.put("scour","Scour means “to search (something) carefully and thoroughly.”");
        eng.put("notorious","Notorious describes people and things that are famously known, especially for something unfavorable.");
        eng.put("utopia","The word utopia refers to “a place of ideal perfection,” ");
        eng.put("defile", "Defile means “to make (something) dirty.”");
        eng.put("peculiar","Peculiar describes people and things that are different from the usual or normal.");
        eng.put("sepulchre","Sepulchre is an old-fashioned word for a tomb or other place of burial. ");
        eng.put("genteel","Genteel means “elegant or graceful in manner, appearance, or shape.”");
        eng.put("volition","Volition is a formal word that means “the power of choosing or determining.” ");
        eng.put("abide","Abide is often used in negative constructions, such as “can't abide,” to say that someone cannot tolerate or accept something");
        eng.put("cloying","Cloying means \"excessively sweet or sentimental.” ");
        eng.put("interlocutor","Interlocutor is a formal word that means “one who takes part in dialogue or conversation.”");
        eng.put("writhe","Writhe means “to twist.”");
        eng.put("bespoke","Bespoke is a synonym of custom-made and is used to describe anything made to an individual’s desired specifications.");
        eng.put("hyperbole","Hyperbole refers to language that describes something as much better or worse than it really is.");
        eng.put("frenetic","Frenetic means “marked by excitement, disorder, or anxiety-driven activity.”");
        eng.put("cadnence","Cadence is used to refer to various rhythmic or repeated motions, activities, or patterns of sound, or to a falling inflection of the voice.");
        eng.put("ineluctable","Ineluctable is a formal word meaning “unable to be avoided, changed, or resisted.”");
        eng.put("oblivion","Oblivion can refer to the state of something that is not remembered, used, or thought about any more, or to the state of being unconscious or unaware.");
        eng.put("osculate","kiss");
        eng.put("transcend","overcome");
        eng.put("muse", "To muse is to ponder or to think,");
        eng.put("ponder","When we ponder, we think carefully about something.");
        eng.put("cogitate","Cogitate means “to think carefully and seriously about something,”");
        eng.put("ruminate","Sometimes we “weigh\" thoughts, sometimes we “turn them over,\" and other times they give us something to “chew on.\" At least that’s what the verb ruminate literally means.");
        eng.put("ideate","We distinguish between thoughts and ideas, and, unsurprisingly, there are verbs in English for producing both.");
        eng.put("intellection","Intellection means “the act of the intellect” or “exercise of the intellect,” a synonym of thought and reasoning. ");
        eng.put("pensive","The literal meaning of pensive is “thoughtful.”");
        eng.put("ratiocination","It means “the process of exact thinking” or “a reasoned train of thought.” ");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");
        eng.put("","");






    }
    public HashMap<String, String> gethishashmap () {
        return this.eng;
    }
}